---
title: "GoodReads Year In Review: 2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    css: style.css
    #source_code: embed
    # theme: flatly
runtime: shiny
    # vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(plotly)
library(bubbles)
source('R/analysis.R')


```

Row 
-----------------------------------------------------------------------

### Books

```{r}

renderValueBox({
  valueBox(
    yearly_summary_long %>%
      filter(measure == 'books') %>%
      pull(`2019`) %>%
      scales::comma(),
    color = '#C27D38'
  )
})

```

### Pages

```{r}

renderValueBox({
  valueBox(
    yearly_summary_long %>%
      filter(measure == 'pages') %>%
      pull(`2019`) %>%
      scales::comma(),
    color = '#C27D38'
  )
})

```

### Pages Read Per Day

```{r}
renderValueBox({
  valueBox(
    yearly_summary_long %>%
      filter(measure == 'avg_pages_per_day') %>%
      pull(`2019`) %>%
      scales::comma(),
    color = '#C27D38'
  )
})
```

### Median Days to Complete

```{r}
renderValueBox({
  valueBox(
    yearly_summary_long %>%
      filter(measure == 'median_days_to_read') %>%
      pull(`2019`) %>%
      scales::comma(),
    color = '#C27D38'
  )
})
```

Row 
-----------------------------------------------------------------------

### Books

```{r}

renderValueBox({
  valueBox(
    yearly_summary_long %>%
      filter(measure == 'books') %>%
      pull(raw_diff) %>%
      scales::comma(),
    caption = 'More books in 2019',
    color = '#CCC591'
    )
})

```

### Pages

```{r}

renderValueBox({
  valueBox(
    yearly_summary_long %>%
      filter(measure == 'pages') %>%
      pull(raw_diff) %>%
      scales::comma(),
    caption = 'More pages in 2019',
    color = '#CCC591'
  )
})

```

### Pages Read Per Day

```{r}
renderValueBox({
  valueBox(
    yearly_summary_long %>%
      filter(measure == 'avg_pages_per_day') %>%
      pull(raw_diff) %>%
      scales::comma(),
    caption = 'Increase in pages per day',
    color = '#CCC591'
  )
})
```

### Median Days to Complete

```{r}
renderValueBox({
  valueBox(
    yearly_summary_long %>%
      filter(measure == 'median_days_to_read') %>%
      pull(raw_diff) %>%
      scales::comma(),
    caption = 'Fewer days per book',
    color = '#CCC591'
  )
})
```

Row {data-height=500}
-----------------------------------------------------------------------

### 2019 Book Calendar

```{r}
ggplotly(p_reading_pace)
```


### Books Read by Monthly

```{r}
p_books_by_month
```

Row {data-height=300}
-----------------------------------------------------------------------


### Top Authors By Pages Read

```{r}
p_authors_pages
```

### Top Authors By Books Read

```{r}
p_authors_books
```


Row {data-height=400}
-----------------------------------------------------------------------

### Top Genre Tags

```{r}

p_top_genres



```

### NRC Sentiment Score Analysis

```{r}

p_sentiments

```









